### ISSUE TITLE
npm install fail on node v13.2.0

### ISSUE THREAD

**Issue by skqksh** [klaytn/caver-js#167]
**Describe the bug**
- npm install fail on node v13.2.0

**How to reproduce**
- command line : npm install caver-js

**Expected behavior**
- should work on node v13.2.0

**Attachments**

```
> keccak@1.4.0 install /usr/src/app/node_modules/keccak
> npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."


> keccak@1.4.0 rebuild /usr/src/app/node_modules/keccak
> node-gyp rebuild

make: Entering directory '/usr/src/app/node_modules/keccak/build'
  CXX(target) Release/obj.target/keccak/src/addon.o
../src/addon.cc: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE KeccakWrapper::Initialize(Nan::NAN_METHOD_ARGS_TYPE)':
../src/addon.cc:37:47: error: no matching function for call to 'v8::Value::IntegerValue()'
     unsigned int rate = info[0]->IntegerValue();
                                               ^
In file included from /root/.cache/node-gyp/13.2.0/include/node/node.h:63:0,
                 from ../src/addon.cc:1:
/root/.cache/node-gyp/13.2.0/include/node/v8.h:2774:40: note: candidate: v8::Maybe<long int> v8::Value::IntegerValue(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
                                        ^~~~~~~~~~~~
/root/.cache/node-gyp/13.2.0/include/node/v8.h:2774:40: note:   candidate expects 1 argument, 0 provided
../src/addon.cc:38:51: error: no matching function for call to 'v8::Value::IntegerValue()'
     unsigned int capacity = info[1]->IntegerValue();
                                                   ^
In file included from /root/.cache/node-gyp/13.2.0/include/node/node.h:63:0,
                 from ../src/addon.cc:1:
/root/.cache/node-gyp/13.2.0/include/node/v8.h:2774:40: note: candidate: v8::Maybe<long int> v8::Value::IntegerValue(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
                                        ^~~~~~~~~~~~
/root/.cache/node-gyp/13.2.0/include/node/v8.h:2774:40: note:   candidate expects 1 argument, 0 provided
../src/addon.cc: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE KeccakWrapper::AbsorbLastFewBits(Nan::NAN_METHOD_ARGS_TYPE)':
../src/addon.cc:56:48: error: no matching function for call to 'v8::Value::IntegerValue()'
     unsigned char bits = info[0]->IntegerValue();
                                                ^
In file included from /root/.cache/node-gyp/13.2.0/include/node/node.h:63:0,
                 from ../src/addon.cc:1:
/root/.cache/node-gyp/13.2.0/include/node/v8.h:2774:40: note: candidate: v8::Maybe<long int> v8::Value::IntegerValue(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
                                        ^~~~~~~~~~~~
/root/.cache/node-gyp/13.2.0/include/node/v8.h:2774:40: note:   candidate expects 1 argument, 0 provided
../src/addon.cc: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE KeccakWrapper::Squeeze(Nan::NAN_METHOD_ARGS_TYPE)':
../src/addon.cc:64:43: error: no matching function for call to 'v8::Value::IntegerValue()'
     size_t length = info[0]->IntegerValue();
                                           ^
In file included from /root/.cache/node-gyp/13.2.0/include/node/node.h:63:0,
                 from ../src/addon.cc:1:
/root/.cache/node-gyp/13.2.0/include/node/v8.h:2774:40: note: candidate: v8::Maybe<long int> v8::Value::IntegerValue(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
                                        ^~~~~~~~~~~~
/root/.cache/node-gyp/13.2.0/include/node/v8.h:2774:40: note:   candidate expects 1 argument, 0 provided
../src/addon.cc: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE KeccakWrapper::Copy(Nan::NAN_METHOD_ARGS_TYPE)':
../src/addon.cc:75:82: error: no matching function for call to 'v8::Value::ToObject()'
     KeccakWrapper* to = Nan::ObjectWrap::Unwrap<KeccakWrapper>(info[0]->ToObject());
                                                                                  ^
In file included from /root/.cache/node-gyp/13.2.0/include/node/node.h:63:0,
                 from ../src/addon.cc:1:
/root/.cache/node-gyp/13.2.0/include/node/v8.h:2754:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^~~~~~~~
/root/.cache/node-gyp/13.2.0/include/node/v8.h:2754:44: note:   candidate expects 1 argument, 0 provided
keccak.target.mk:127: recipe for target 'Release/obj.target/keccak/src/addon.o' failed
make: Leaving directory '/usr/src/app/node_modules/keccak/build'
make: *** [Release/obj.target/keccak/src/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
gyp ERR! System Linux 4.9.184-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/src/app/node_modules/keccak
gyp ERR! node -v v13.2.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-02T01_00_06_241Z-debug.log
Keccak bindings compilation fail. Pure JS implementation will be used.

> secp256k1@3.7.1 install /usr/src/app/node_modules/secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."


> secp256k1@3.7.1 rebuild /usr/src/app/node_modules/secp256k1
> node-gyp rebuild

make: Entering directory '/usr/src/app/node_modules/secp256k1/build'
  CXX(target) Release/obj.target/secp256k1/src/addon.o
  CXX(target) Release/obj.target/secp256k1/src/privatekey.o
../src/privatekey.cc: In function 'Nan::NAN_METHOD_RETURN_TYPE privateKeyNegate(Nan::NAN_METHOD_ARGS_TYPE)':
../src/privatekey.cc:73:61: warning: ignoring return value of 'int secp256k1_ec_privkey_negate(const secp256k1_context*, unsigned char*)', declared with attribute warn_unused_result [-Wunused-result]
   secp256k1_ec_privkey_negate(secp256k1ctx, &private_key[0]);
                                                             ^
  CXX(target) Release/obj.target/secp256k1/src/publickey.o
  CXX(target) Release/obj.target/secp256k1/src/signature.o
  CXX(target) Release/obj.target/secp256k1/src/ecdsa.o
  CXX(target) Release/obj.target/secp256k1/src/ecdh.o
  CC(target) Release/obj.target/secp256k1/src/secp256k1-src/src/secp256k1.o
  CC(target) Release/obj.target/secp256k1/src/secp256k1-src/contrib/lax_der_parsing.o
  CC(target) Release/obj.target/secp256k1/src/secp256k1-src/contrib/lax_der_privatekey_parsing.o
  SOLINK_MODULE(target) Release/obj.target/secp256k1.node
  COPY Release/secp256k1.node
make: Leaving directory '/usr/src/app/node_modules/secp256k1/build'

> websocket@1.0.30 install /usr/src/app/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/usr/src/app/node_modules/websocket/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
bufferutil.target.mk:110: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
make: Leaving directory '/usr/src/app/node_modules/websocket/build'
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.
```

**Environment (please complete the following information)**
 - caver-js : ^1.2.1
 - Dockerfile : FROM node:13.2.0

**Additional context**

**Comment by jimni1222** [comment]
This issue is resolved by @skqksh , so i will close this. :) 
Thank you for contribution again.
